### ISSUE TITLE
Converting into a Gem

### ISSUE THREAD

**Issue by tomlazar** [chacha/thebluealliance-ruby#2]
Have you considered making this into a gem so people who want to use it can access it easier?

**Comment by tylerhcarter** [comment]
@TomRaven I haven't considered it, mostly due to my inexperience with Ruby. I'm not sure what exactly gem-ifying a source code set entails. But, if it is something you'd be interested in doing, I'm all ears.

**Comment by tomlazar** [comment]
@chacha I am fairly new to Ruby as well, but I want to learn more. 

RubyGems.org has a guide on how to gem-ify some source code [here](http://guides.rubygems.org/make-your-own-gem/), and if you don't mind I would love to try and go through it and make your blue alliance into a ruby Gem.
